# Generated by Django 4.0.6 on 2022-08-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_studentresult_course_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
