# Generated by Django 4.0.6 on 2022-08-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_studentresult'),
        ('hod', '0003_student_alter_enroll_student'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
